/**
 * QA Monster - Report Generator
 *
 * Formats findings into comprehensive, reviewable reports.
 */

import {
  Finding,
  generateFindingId,
  resetFindingCounter,
} from "./monster-config";

export function formatFindingsReport(
  findings: Finding[],
  runInfo: {
    date: string;
    duration: string;
    pagesScanned: number;
    viewportsTested: number;
    flowsCompleted: number;
  },
): string {
  resetFindingCounter();

  const bugs = findings.filter((f) => f.category === "BUG");
  const issues = findings.filter((f) => f.category === "ISSUE");
  const concerns = findings.filter((f) => f.category === "CONCERN");
  const opinions = findings.filter((f) => f.category === "OPINION");

  const critical = findings.filter((f) => f.severity === "critical");
  const high = findings.filter((f) => f.severity === "high");
  const medium = findings.filter((f) => f.severity === "medium");
  const low = findings.filter((f) => f.severity === "low");
  const notes = findings.filter((f) => f.severity === "note");

  return `# QA Monster Report

**Generated:** ${runInfo.date}
**Duration:** ${runInfo.duration}
**Scope:** ${runInfo.pagesScanned} pages × ${runInfo.viewportsTested} viewports
**Flows Tested:** ${runInfo.flowsCompleted}

---

## Executive Summary

| Category | Count |
|----------|-------|
| 🐛 Bugs | ${bugs.length} |
| ⚠️ Issues | ${issues.length} |
| 🤔 Concerns | ${concerns.length} |
| 💭 Opinions | ${opinions.length} |
| **Total** | **${findings.length}** |

| Severity | Count |
|----------|-------|
| 🔴 Critical | ${critical.length} |
| 🟠 High | ${high.length} |
| 🟡 Medium | ${medium.length} |
| 🟢 Low | ${low.length} |
| 📝 Notes | ${notes.length} |

${
  critical.length > 0
    ? `
### ⚠️ CRITICAL ISSUES REQUIRING IMMEDIATE ATTENTION

${critical.map((f) => `- **${f.id}**: ${f.title} (${f.page})`).join("\n")}
`
    : ""
}

---

## 🐛 Bugs (Must Fix)

${bugs.length === 0 ? "_No bugs found._" : bugs.map((f) => formatFinding(f)).join("\n\n---\n\n")}

---

## ⚠️ Issues (Should Fix)

${issues.length === 0 ? "_No issues found._" : issues.map((f) => formatFinding(f)).join("\n\n---\n\n")}

---

## 🤔 Concerns (Consider Fixing)

${concerns.length === 0 ? "_No concerns raised._" : concerns.map((f) => formatFinding(f)).join("\n\n---\n\n")}

---

## 💭 Opinions (Discuss)

${opinions.length === 0 ? "_No opinions to share._" : opinions.map((f) => formatFinding(f)).join("\n\n---\n\n")}

---

## Findings by Page

${groupByPage(findings)}

---

## Tags Index

${generateTagIndex(findings)}

---

## Recommendations

### Immediate Actions (This Week)
${critical.map((f) => `- [ ] Fix ${f.id}: ${f.title}`).join("\n") || "_None_"}
${high
  .slice(0, 5)
  .map((f) => `- [ ] Fix ${f.id}: ${f.title}`)
  .join("\n")}

### Short-term (This Sprint)
${
  high
    .slice(5)
    .concat(medium.slice(0, 10))
    .map((f) => `- [ ] Address ${f.id}: ${f.title}`)
    .join("\n") || "_None_"
}

### Consider Later
${
  medium
    .slice(10)
    .concat(low)
    .slice(0, 10)
    .map((f) => `- [ ] Review ${f.id}: ${f.title}`)
    .join("\n") || "_None_"
}

---

## Monster's Overall Opinion

_To be filled after review:_

- **First Impression:**
- **Visual Polish:** /10
- **UX Quality:** /10
- **Consistency:** /10
- **Production Readiness:** /10
- **Most Critical Issue:**
- **Quick Win:**
- **Final Grade:**

---

_Report generated by QA Monster v1.0_
`;
}

function formatFinding(f: Finding): string {
  const severityIcon = {
    critical: "🔴",
    high: "🟠",
    medium: "🟡",
    low: "🟢",
    note: "📝",
  }[f.severity];

  return `### ${f.id}: ${f.title}

**Severity:** ${severityIcon} ${f.severity.charAt(0).toUpperCase() + f.severity.slice(1)}
**Page:** ${f.page}
${f.viewport ? `**Viewport:** ${f.viewport}` : ""}
${f.screenshot ? `**Screenshot:** ${f.screenshot}` : ""}
**Tags:** ${f.tags.map((t) => `\`${t}\``).join(", ")}

**Description:**
${f.description}

${
  f.expected
    ? `**Expected:**
${f.expected}

`
    : ""
}${
    f.actual
      ? `**Actual:**
${f.actual}

`
      : ""
  }${
    f.opinion
      ? `**My Opinion:**
${f.opinion}

`
      : ""
  }${
    f.suggestion
      ? `**Suggested Fix:**
${f.suggestion}`
      : ""
  }`;
}

function groupByPage(findings: Finding[]): string {
  const byPage: Record<string, Finding[]> = {};

  for (const f of findings) {
    if (!byPage[f.page]) byPage[f.page] = [];
    byPage[f.page].push(f);
  }

  return Object.entries(byPage)
    .sort((a, b) => b[1].length - a[1].length)
    .map(([page, pageFindings]) => {
      const bugs = pageFindings.filter((f) => f.category === "BUG").length;
      const issues = pageFindings.filter((f) => f.category === "ISSUE").length;
      const concerns = pageFindings.filter(
        (f) => f.category === "CONCERN",
      ).length;
      const opinions = pageFindings.filter(
        (f) => f.category === "OPINION",
      ).length;

      return `### ${page}
| Type | Count |
|------|-------|
| Bugs | ${bugs} |
| Issues | ${issues} |
| Concerns | ${concerns} |
| Opinions | ${opinions} |

Findings: ${pageFindings.map((f) => f.id).join(", ")}`;
    })
    .join("\n\n");
}

function generateTagIndex(findings: Finding[]): string {
  const tagCounts: Record<string, number> = {};

  for (const f of findings) {
    for (const tag of f.tags) {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1;
    }
  }

  return Object.entries(tagCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([tag, count]) => `- \`${tag}\`: ${count} findings`)
    .join("\n");
}

// Export for programmatic use
export { formatFinding, groupByPage, generateTagIndex };
