#!/usr/bin/env npx ts-node
/**
 * Monster Army - Cleanup Utility
 *
 * Cleans up old data generated by the Monster Army:
 * - Iteration reports
 * - Triage reports
 * - Memory store (old runs/findings)
 * - Auto-generated test files
 *
 * Run: npx ts-node tests/qa/monsters/cleanup.ts [options]
 *
 * Options:
 *   --dry-run       Show what would be deleted without deleting
 *   --all           Delete everything (reset to clean state)
 *   --keep-days N   Keep data from last N days (default: 7)
 *   --keep-runs N   Keep last N runs in memory store (default: 20)
 */

import {
  existsSync,
  readdirSync,
  unlinkSync,
  statSync,
  writeFileSync,
  readFileSync,
  rmSync,
} from "fs";
import { join } from "path";

// ============================================================================
// CONFIGURATION
// ============================================================================

interface CleanupConfig {
  dryRun: boolean;
  keepDays: number;
  keepRuns: number;
  deleteAll: boolean;
}

const DEFAULT_CONFIG: CleanupConfig = {
  dryRun: false,
  keepDays: 7,
  keepRuns: 20,
  deleteAll: false,
};

// Paths to clean
const PATHS = {
  iterationReports: "tests/qa/monsters/reports/iterations",
  triageReports: "tests/qa/monsters/reports",
  memoryStore: "tests/qa/monsters/data/memory.json",
  autoGenerated: "tests/qa/monsters/auto-generated",
  evolutionReports: "tests/qa/monsters/reports/evolution",
};

// ============================================================================
// CLEANUP FUNCTIONS
// ============================================================================

interface CleanupStats {
  filesDeleted: number;
  bytesFreed: number;
  runsRemoved: number;
  findingsRemoved: number;
}

function cleanIterationReports(config: CleanupConfig): CleanupStats {
  const stats: CleanupStats = {
    filesDeleted: 0,
    bytesFreed: 0,
    runsRemoved: 0,
    findingsRemoved: 0,
  };
  const dir = join(process.cwd(), PATHS.iterationReports);

  if (!existsSync(dir)) {
    console.log("  ⏭️  No iteration reports directory found");
    return stats;
  }

  const files = readdirSync(dir).filter((f) => f.endsWith(".json"));
  const cutoffDate = new Date(
    Date.now() - config.keepDays * 24 * 60 * 60 * 1000,
  );

  console.log(`  📁 Found ${files.length} iteration report files`);

  for (const file of files) {
    const filePath = join(dir, file);
    const fileStat = statSync(filePath);

    if (config.deleteAll || fileStat.mtime < cutoffDate) {
      stats.bytesFreed += fileStat.size;
      stats.filesDeleted++;

      if (config.dryRun) {
        console.log(
          `    [DRY RUN] Would delete: ${file} (${formatBytes(fileStat.size)})`,
        );
      } else {
        unlinkSync(filePath);
        console.log(`    ✅ Deleted: ${file} (${formatBytes(fileStat.size)})`);
      }
    }
  }

  return stats;
}

function cleanTriageReports(config: CleanupConfig): CleanupStats {
  const stats: CleanupStats = {
    filesDeleted: 0,
    bytesFreed: 0,
    runsRemoved: 0,
    findingsRemoved: 0,
  };
  const dir = join(process.cwd(), PATHS.triageReports);

  if (!existsSync(dir)) {
    return stats;
  }

  const files = readdirSync(dir).filter(
    (f) => f.startsWith("triage-") && f.endsWith(".json"),
  );
  const cutoffDate = new Date(
    Date.now() - config.keepDays * 24 * 60 * 60 * 1000,
  );

  console.log(`  📁 Found ${files.length} triage report files`);

  for (const file of files) {
    const filePath = join(dir, file);
    const fileStat = statSync(filePath);

    if (config.deleteAll || fileStat.mtime < cutoffDate) {
      stats.bytesFreed += fileStat.size;
      stats.filesDeleted++;

      if (config.dryRun) {
        console.log(
          `    [DRY RUN] Would delete: ${file} (${formatBytes(fileStat.size)})`,
        );
      } else {
        unlinkSync(filePath);
        console.log(`    ✅ Deleted: ${file} (${formatBytes(fileStat.size)})`);
      }
    }
  }

  return stats;
}

function cleanMemoryStore(config: CleanupConfig): CleanupStats {
  const stats: CleanupStats = {
    filesDeleted: 0,
    bytesFreed: 0,
    runsRemoved: 0,
    findingsRemoved: 0,
  };
  const memoryPath = join(process.cwd(), PATHS.memoryStore);

  if (!existsSync(memoryPath)) {
    console.log("  ⏭️  No memory store found");
    return stats;
  }

  const originalSize = statSync(memoryPath).size;

  if (config.deleteAll) {
    // Complete reset
    if (config.dryRun) {
      console.log(
        `  [DRY RUN] Would reset memory store (${formatBytes(originalSize)})`,
      );
    } else {
      const emptyStore = {
        version: 1,
        lastUpdated: new Date().toISOString(),
        runs: [],
        findings: [],
        coverageGaps: [],
      };
      writeFileSync(memoryPath, JSON.stringify(emptyStore, null, 2));
      stats.bytesFreed = originalSize;
      console.log(
        `  ✅ Reset memory store (freed ${formatBytes(originalSize)})`,
      );
    }
    return stats;
  }

  // Partial cleanup - keep recent runs and relevant findings
  try {
    const data = JSON.parse(readFileSync(memoryPath, "utf-8"));
    const originalRuns = data.runs?.length || 0;
    const originalFindings = data.findings?.length || 0;

    // Keep only the last N runs
    if (data.runs && data.runs.length > config.keepRuns) {
      const removedRuns = data.runs.length - config.keepRuns;
      data.runs = data.runs.slice(-config.keepRuns);
      stats.runsRemoved = removedRuns;
    }

    // Get fingerprints from remaining runs
    const activeFingerprints = new Set<string>();
    for (const run of data.runs || []) {
      for (const fp of run.findingIds || []) {
        activeFingerprints.add(fp);
      }
    }

    // Remove findings not in recent runs (unless they're open)
    if (Array.isArray(data.findings)) {
      const originalFindingsCount = data.findings.length;
      data.findings = data.findings.filter((f: any) => {
        // Keep open findings
        if (f.status === "open") return true;
        // Keep findings from recent runs
        if (activeFingerprints.has(f.fingerprint)) return true;
        // Remove old fixed findings
        return false;
      });
      stats.findingsRemoved = originalFindingsCount - data.findings.length;
    }

    // Update and save
    data.lastUpdated = new Date().toISOString();

    if (config.dryRun) {
      console.log(
        `  [DRY RUN] Would remove ${stats.runsRemoved} runs, ${stats.findingsRemoved} findings`,
      );
    } else {
      writeFileSync(memoryPath, JSON.stringify(data, null, 2));
      const newSize = statSync(memoryPath).size;
      stats.bytesFreed = originalSize - newSize;
      console.log(`  ✅ Cleaned memory store:`);
      console.log(
        `     Runs: ${originalRuns} → ${data.runs.length} (removed ${stats.runsRemoved})`,
      );
      console.log(
        `     Findings: ${originalFindings} → ${data.findings.length} (removed ${stats.findingsRemoved})`,
      );
      console.log(
        `     Size: ${formatBytes(originalSize)} → ${formatBytes(newSize)} (freed ${formatBytes(stats.bytesFreed)})`,
      );
    }
  } catch (e) {
    console.log(`  ⚠️  Could not parse memory store: ${e}`);
  }

  return stats;
}

function cleanAutoGenerated(config: CleanupConfig): CleanupStats {
  const stats: CleanupStats = {
    filesDeleted: 0,
    bytesFreed: 0,
    runsRemoved: 0,
    findingsRemoved: 0,
  };
  const dir = join(process.cwd(), PATHS.autoGenerated);

  if (!existsSync(dir)) {
    console.log("  ⏭️  No auto-generated directory found");
    return stats;
  }

  const files = readdirSync(dir).filter(
    (f) => f !== ".gitkeep" && f !== "README.md",
  );

  if (files.length === 0) {
    console.log("  ⏭️  No auto-generated files to clean");
    return stats;
  }

  console.log(`  📁 Found ${files.length} auto-generated files`);

  const cutoffDate = new Date(
    Date.now() - config.keepDays * 24 * 60 * 60 * 1000,
  );

  for (const file of files) {
    const filePath = join(dir, file);
    const fileStat = statSync(filePath);

    if (config.deleteAll || fileStat.mtime < cutoffDate) {
      stats.bytesFreed += fileStat.size;
      stats.filesDeleted++;

      if (config.dryRun) {
        console.log(
          `    [DRY RUN] Would delete: ${file} (${formatBytes(fileStat.size)})`,
        );
      } else {
        if (fileStat.isDirectory()) {
          rmSync(filePath, { recursive: true });
        } else {
          unlinkSync(filePath);
        }
        console.log(`    ✅ Deleted: ${file} (${formatBytes(fileStat.size)})`);
      }
    }
  }

  return stats;
}

// ============================================================================
// UTILITIES
// ============================================================================

function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + " " + sizes[i];
}

function parseArgs(): CleanupConfig {
  const args = process.argv.slice(2);
  const config = { ...DEFAULT_CONFIG };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    if (arg === "--dry-run") {
      config.dryRun = true;
    } else if (arg === "--all") {
      config.deleteAll = true;
    } else if (arg === "--keep-days" && args[i + 1]) {
      config.keepDays = parseInt(args[++i], 10);
    } else if (arg === "--keep-runs" && args[i + 1]) {
      config.keepRuns = parseInt(args[++i], 10);
    } else if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    }
  }

  return config;
}

function printHelp(): void {
  console.log(`
Monster Army Cleanup Utility

Usage: npx ts-node tests/qa/monsters/cleanup.ts [options]

Options:
  --dry-run       Show what would be deleted without actually deleting
  --all           Delete everything (complete reset)
  --keep-days N   Keep data from last N days (default: 7)
  --keep-runs N   Keep last N runs in memory store (default: 20)
  --help, -h      Show this help message

Examples:
  # See what would be deleted (safe preview)
  npx ts-node tests/qa/monsters/cleanup.ts --dry-run

  # Keep only last 3 days of data
  npx ts-node tests/qa/monsters/cleanup.ts --keep-days 3

  # Complete reset - delete all monster data
  npx ts-node tests/qa/monsters/cleanup.ts --all

  # Keep only last 10 runs
  npx ts-node tests/qa/monsters/cleanup.ts --keep-runs 10
`);
}

// ============================================================================
// MAIN
// ============================================================================

function main(): void {
  const config = parseArgs();

  console.log("\n" + "═".repeat(60));
  console.log("  🧹 MONSTER ARMY - CLEANUP UTILITY");
  console.log("═".repeat(60) + "\n");

  if (config.dryRun) {
    console.log("  ⚠️  DRY RUN MODE - No files will be deleted\n");
  }

  if (config.deleteAll) {
    console.log("  🚨 FULL RESET MODE - All data will be deleted\n");
  } else {
    console.log(`  📅 Keeping data from last ${config.keepDays} days`);
    console.log(`  📊 Keeping last ${config.keepRuns} runs in memory\n`);
  }

  const totalStats: CleanupStats = {
    filesDeleted: 0,
    bytesFreed: 0,
    runsRemoved: 0,
    findingsRemoved: 0,
  };

  // Clean each area
  console.log("━".repeat(60));
  console.log("  Iteration Reports");
  console.log("━".repeat(60));
  const iterStats = cleanIterationReports(config);
  totalStats.filesDeleted += iterStats.filesDeleted;
  totalStats.bytesFreed += iterStats.bytesFreed;

  console.log("\n" + "━".repeat(60));
  console.log("  Triage Reports");
  console.log("━".repeat(60));
  const triageStats = cleanTriageReports(config);
  totalStats.filesDeleted += triageStats.filesDeleted;
  totalStats.bytesFreed += triageStats.bytesFreed;

  console.log("\n" + "━".repeat(60));
  console.log("  Memory Store");
  console.log("━".repeat(60));
  const memoryStats = cleanMemoryStore(config);
  totalStats.bytesFreed += memoryStats.bytesFreed;
  totalStats.runsRemoved = memoryStats.runsRemoved;
  totalStats.findingsRemoved = memoryStats.findingsRemoved;

  console.log("\n" + "━".repeat(60));
  console.log("  Auto-Generated Files");
  console.log("━".repeat(60));
  const autoGenStats = cleanAutoGenerated(config);
  totalStats.filesDeleted += autoGenStats.filesDeleted;
  totalStats.bytesFreed += autoGenStats.bytesFreed;

  // Summary
  console.log("\n" + "═".repeat(60));
  console.log("  CLEANUP SUMMARY");
  console.log("═".repeat(60));

  if (config.dryRun) {
    console.log("\n  [DRY RUN] Would have:");
  } else {
    console.log("\n  Completed:");
  }

  console.log(`    📄 Files deleted: ${totalStats.filesDeleted}`);
  console.log(`    📊 Runs removed: ${totalStats.runsRemoved}`);
  console.log(`    🔍 Findings removed: ${totalStats.findingsRemoved}`);
  console.log(`    💾 Space freed: ${formatBytes(totalStats.bytesFreed)}`);

  console.log("\n" + "═".repeat(60) + "\n");

  if (config.dryRun && totalStats.filesDeleted > 0) {
    console.log("  💡 Run without --dry-run to actually delete files\n");
  }
}

main();
